-- Create table
CREATE TABLE Player (
    PlayerID INT PRIMARY KEY,
    PlayerName NVARCHAR(100) NOT NULL,
    Nation NVARCHAR(50) NOT NULL
);

-- Sort alphabetically
INSERT INTO Player (PlayerID, PlayerName, Nation) VALUES
(1, '4laps2win', 'UK'),
(2, 'Albert', 'USA'),
(3, 'Alberto', 'Spain'),
(4, 'Alpaco', 'Netherlands'),
(5, 'ain', 'Japan'),
(6, 'alpha', 'Germany'),
(7, 'Army', 'France'),
(8, 'Bruh', 'USA'),
(9, 'Byron', 'Australia'),
(10, 'Draygo', 'USA'),
(11, 'エル', 'Japan'),
(12, 'F。', 'Japan'),
(13, 'Jamie', 'UK'),
(14, 'JenZua', 'Spain'),
(15, 'L', 'Japan'),
(16, 'Messi', 'USA'),
(17, 'Miguel', 'USA'),
(18, 'Mirai', 'USA'),
(19, 'Nanew', 'Germany'),
(20, 'Panda', 'Australia'),
(21, 'Pii', 'Norway'),
(22, 'SKaR', 'UK'),
(23, 'StervtL', 'Netherlands'),
(24, 'Technical', 'USA'),
(25, 'Tane', 'Japan'),
(26, 'Vincent', 'USA'),
(27, 'Wish', 'France'),
(28, 'Yerson', 'Colombia'),
(29, 'YUTM', 'Japan'),
(30, 'Zae', 'USA'),
(31, 'ありす', 'Japan'),
(32, 'ありすがわ', 'Japan'),
(33, 'ゆず', 'Japan'),
(34, 'ゆうっち', 'Japan'),
(35, 'おにぎりザウルス', 'Japan'),
(36, 'くぜろ', 'Japan'),
(37, 'ぐち', 'Japan'),
(38, 'なすの', 'Japan'),
(39, 'のり', 'Japan'),
(40, 'そーなのかー', 'Japan'),
(41, 'ろーる', 'Japan'),
(42, 'ヨッシ', 'Japan'),
(43, '¥146', 'Japan'),
(44, 'grace', 'USA'),
(45, 'kisaragi', 'Japan'),
(46, 'Matt', 'Canada'),
(47, 'もぺち', 'Japan');
